name: Build My App
on: [push] # This means: "Every time I save code to GitHub, build an APK"

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npx cap sync android
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: my-app-file
          path: android/app/build/outputs/apk/debug/app-debug.apk
